# Generated by Django 3.1 on 2020-09-05 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealtoorders',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.meals'),
        ),
        migrations.AddField(
            model_name='mealtoorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.orders'),
        ),
        migrations.AddField(
            model_name='meals',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.mealcategories'),
        ),
        migrations.AddField(
            model_name='mealcategories',
            name='departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.departments'),
        ),
        migrations.AddField(
            model_name='checks',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.orders'),
        ),
        migrations.AddField(
            model_name='checks',
            name='percentage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicepercentage'),
        ),
    ]
