# Generated by Django 3.1 on 2020-09-01 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.statuses')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.tables')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealToOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.meals')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('oreder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.orders')),
                ('percentage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicepercentage')),
            ],
        ),
    ]
