# Generated by Django 3.1 on 2020-09-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_checks_mealtoorders_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checks',
            old_name='oreder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='mealtoorders',
            old_name='orders',
            new_name='order',
        ),
    ]
