# Generated by Django 3.1 on 2020-09-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200904_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(choices=[('1', 'Waiter'), ('2', 'Admin'), ('3', 'Chef')], max_length=20),
        ),
    ]
