# Generated by Django 3.1 on 2020-09-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200911_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtoorders',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='meals',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='service.mealtoorders'),
        ),
    ]
