# Generated by Django 3.1 on 2020-09-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200904_2013'),
        ('service', '0004_auto_20200904_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
