# Generated by Django 3.1 on 2020-09-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_delete_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Waiter', 'Waiter'), ('Admin', 'Admin'), ('Chef', 'Chef')], max_length=20)),
            ],
        ),
    ]
