# Generated by Django 3.1 on 2020-09-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200911_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='percentage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.servicepercentage'),
        ),
    ]
