# Generated by Django 3.1 on 2020-09-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200904_1640'),
        ('user', '0005_auto_20200901_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.CASCADE, to='service.roles'),
        ),
    ]
