# Generated by Django 3.1 on 2020-09-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200904_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Waiter', 'Waiter'), ('Admin', 'Admin'), ('Chef', 'Chef')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.CASCADE, to='user.roles'),
        ),
    ]
