# Generated by Django 3.1 on 2020-09-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_roles'),
        ('user', '0012_auto_20200904_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.CASCADE, to='service.roles'),
        ),
    ]
