# Generated by Django 3.1 on 2020-09-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
